using System;
using System.Net.Http;

namespace Imagekit.Models.Accounts.URLEndpoints;

/// <summary>
/// **Note:** This API is currently in beta.   Returns an array of all URL‑endpoints
/// configured including the default URL-endpoint generated by ImageKit during account
/// creation.
/// </summary>
public sealed record class URLEndpointListParams : ParamsBase
{
    public override Uri Url(IImageKitClient client)
    {
        return new UriBuilder(client.BaseUrl.ToString().TrimEnd('/') + "/v1/accounts/url-endpoints")
        {
            Query = this.QueryString(client),
        }.Uri;
    }

    public void AddHeadersToRequest(HttpRequestMessage request, IImageKitClient client)
    {
        ParamsBase.AddDefaultHeaders(request, client);
        foreach (var item in this.HeaderProperties)
        {
            ParamsBase.AddHeaderElementToRequest(request, item.Key, item.Value);
        }
    }
}
