using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using ImageKit.Core;
using ImageKit.Exceptions;

namespace ImageKit.Models.Accounts.UrlEndpoints;

/// <summary>
/// URL‑endpoint object as returned by the API.
/// </summary>
[JsonConverter(typeof(JsonModelConverter<UrlEndpointResponse, UrlEndpointResponseFromRaw>))]
public sealed record class UrlEndpointResponse : JsonModel
{
    /// <summary>
    /// Unique identifier for the URL-endpoint. This is generated by ImageKit when
    /// you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.
    /// </summary>
    public required string ID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("id");
        }
        init { this._rawData.Set("id", value); }
    }

    /// <summary>
    /// Description of the URL endpoint.
    /// </summary>
    public required string Description
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("description");
        }
        init { this._rawData.Set("description", value); }
    }

    /// <summary>
    /// Ordered list of origin IDs to try when the file isn’t in the Media Library;
    /// ImageKit checks them in the sequence provided. Origin must be created before
    /// it can be used in a URL endpoint.
    /// </summary>
    public required IReadOnlyList<string> Origins
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<ImmutableArray<string>>("origins");
        }
        init
        {
            this._rawData.Set<ImmutableArray<string>>(
                "origins",
                ImmutableArray.ToImmutableArray(value)
            );
        }
    }

    /// <summary>
    /// Path segment appended to your base URL to form the endpoint (letters, digits,
    /// and hyphens only — or empty for the default endpoint).
    /// </summary>
    public required string UrlPrefix
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("urlPrefix");
        }
        init { this._rawData.Set("urlPrefix", value); }
    }

    /// <summary>
    /// Configuration for third-party URL rewriting.
    /// </summary>
    public UrlEndpointResponseUrlRewriter? UrlRewriter
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<UrlEndpointResponseUrlRewriter>("urlRewriter");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("urlRewriter", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.ID;
        _ = this.Description;
        _ = this.Origins;
        _ = this.UrlPrefix;
        this.UrlRewriter?.Validate();
    }

    public UrlEndpointResponse() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public UrlEndpointResponse(UrlEndpointResponse urlEndpointResponse)
        : base(urlEndpointResponse) { }
#pragma warning restore CS8618

    public UrlEndpointResponse(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    UrlEndpointResponse(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="UrlEndpointResponseFromRaw.FromRawUnchecked"/>
    public static UrlEndpointResponse FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class UrlEndpointResponseFromRaw : IFromRawJson<UrlEndpointResponse>
{
    /// <inheritdoc/>
    public UrlEndpointResponse FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        UrlEndpointResponse.FromRawUnchecked(rawData);
}

/// <summary>
/// Configuration for third-party URL rewriting.
/// </summary>
[JsonConverter(typeof(UrlEndpointResponseUrlRewriterConverter))]
public record class UrlEndpointResponseUrlRewriter : ModelBase
{
    public object? Value { get; } = null;

    JsonElement? _element = null;

    public JsonElement Json
    {
        get
        {
            return this._element ??= JsonSerializer.SerializeToElement(
                this.Value,
                ModelBase.SerializerOptions
            );
        }
    }

    public UrlEndpointResponseUrlRewriter(
        UrlEndpointResponseUrlRewriterCloudinary value,
        JsonElement? element = null
    )
    {
        this.Value = value;
        this._element = element;
    }

    public UrlEndpointResponseUrlRewriter(
        UrlEndpointResponseUrlRewriterImgix value,
        JsonElement? element = null
    )
    {
        this.Value = value;
        this._element = element;
    }

    public UrlEndpointResponseUrlRewriter(
        UrlEndpointResponseUrlRewriterAkamai value,
        JsonElement? element = null
    )
    {
        this.Value = value;
        this._element = element;
    }

    public UrlEndpointResponseUrlRewriter(JsonElement element)
    {
        this._element = element;
    }

    /// <summary>
    /// Returns true and sets the <c>out</c> parameter if the instance was constructed with a variant of
    /// type <see cref="UrlEndpointResponseUrlRewriterCloudinary"/>.
    ///
    /// <para>Consider using <see cref="Switch"/> or <see cref="Match"/> if you need to handle every variant.</para>
    ///
    /// <example>
    /// <code>
    /// if (instance.TryPickCloudinary(out var value)) {
    ///     // `value` is of type `UrlEndpointResponseUrlRewriterCloudinary`
    ///     Console.WriteLine(value);
    /// }
    /// </code>
    /// </example>
    /// </summary>
    public bool TryPickCloudinary(
        [NotNullWhen(true)] out UrlEndpointResponseUrlRewriterCloudinary? value
    )
    {
        value = this.Value as UrlEndpointResponseUrlRewriterCloudinary;
        return value != null;
    }

    /// <summary>
    /// Returns true and sets the <c>out</c> parameter if the instance was constructed with a variant of
    /// type <see cref="UrlEndpointResponseUrlRewriterImgix"/>.
    ///
    /// <para>Consider using <see cref="Switch"/> or <see cref="Match"/> if you need to handle every variant.</para>
    ///
    /// <example>
    /// <code>
    /// if (instance.TryPickImgix(out var value)) {
    ///     // `value` is of type `UrlEndpointResponseUrlRewriterImgix`
    ///     Console.WriteLine(value);
    /// }
    /// </code>
    /// </example>
    /// </summary>
    public bool TryPickImgix([NotNullWhen(true)] out UrlEndpointResponseUrlRewriterImgix? value)
    {
        value = this.Value as UrlEndpointResponseUrlRewriterImgix;
        return value != null;
    }

    /// <summary>
    /// Returns true and sets the <c>out</c> parameter if the instance was constructed with a variant of
    /// type <see cref="UrlEndpointResponseUrlRewriterAkamai"/>.
    ///
    /// <para>Consider using <see cref="Switch"/> or <see cref="Match"/> if you need to handle every variant.</para>
    ///
    /// <example>
    /// <code>
    /// if (instance.TryPickAkamai(out var value)) {
    ///     // `value` is of type `UrlEndpointResponseUrlRewriterAkamai`
    ///     Console.WriteLine(value);
    /// }
    /// </code>
    /// </example>
    /// </summary>
    public bool TryPickAkamai([NotNullWhen(true)] out UrlEndpointResponseUrlRewriterAkamai? value)
    {
        value = this.Value as UrlEndpointResponseUrlRewriterAkamai;
        return value != null;
    }

    /// <summary>
    /// Calls the function parameter corresponding to the variant the instance was constructed with.
    ///
    /// <para>Use the <c>TryPick</c> method(s) if you don't need to handle every variant, or <see cref="Match"/>
    /// if you need your function parameters to return something.</para>
    ///
    /// <exception cref="ImageKitInvalidDataException">
    /// Thrown when the instance was constructed with an unknown variant (e.g. deserialized from raw data
    /// that doesn't match any variant's expected shape).
    /// </exception>
    ///
    /// <example>
    /// <code>
    /// instance.Switch(
    ///     (UrlEndpointResponseUrlRewriterCloudinary value) =&gt; {...},
    ///     (UrlEndpointResponseUrlRewriterImgix value) =&gt; {...},
    ///     (UrlEndpointResponseUrlRewriterAkamai value) =&gt; {...}
    /// );
    /// </code>
    /// </example>
    /// </summary>
    public void Switch(
        Action<UrlEndpointResponseUrlRewriterCloudinary> cloudinary,
        Action<UrlEndpointResponseUrlRewriterImgix> imgix,
        Action<UrlEndpointResponseUrlRewriterAkamai> akamai
    )
    {
        switch (this.Value)
        {
            case UrlEndpointResponseUrlRewriterCloudinary value:
                cloudinary(value);
                break;
            case UrlEndpointResponseUrlRewriterImgix value:
                imgix(value);
                break;
            case UrlEndpointResponseUrlRewriterAkamai value:
                akamai(value);
                break;
            default:
                throw new ImageKitInvalidDataException(
                    "Data did not match any variant of UrlEndpointResponseUrlRewriter"
                );
        }
    }

    /// <summary>
    /// Calls the function parameter corresponding to the variant the instance was constructed with and
    /// returns its result.
    ///
    /// <para>Use the <c>TryPick</c> method(s) if you don't need to handle every variant, or <see cref="Switch"/>
    /// if you don't need your function parameters to return a value.</para>
    ///
    /// <exception cref="ImageKitInvalidDataException">
    /// Thrown when the instance was constructed with an unknown variant (e.g. deserialized from raw data
    /// that doesn't match any variant's expected shape).
    /// </exception>
    ///
    /// <example>
    /// <code>
    /// var result = instance.Match(
    ///     (UrlEndpointResponseUrlRewriterCloudinary value) =&gt; {...},
    ///     (UrlEndpointResponseUrlRewriterImgix value) =&gt; {...},
    ///     (UrlEndpointResponseUrlRewriterAkamai value) =&gt; {...}
    /// );
    /// </code>
    /// </example>
    /// </summary>
    public T Match<T>(
        Func<UrlEndpointResponseUrlRewriterCloudinary, T> cloudinary,
        Func<UrlEndpointResponseUrlRewriterImgix, T> imgix,
        Func<UrlEndpointResponseUrlRewriterAkamai, T> akamai
    )
    {
        return this.Value switch
        {
            UrlEndpointResponseUrlRewriterCloudinary value => cloudinary(value),
            UrlEndpointResponseUrlRewriterImgix value => imgix(value),
            UrlEndpointResponseUrlRewriterAkamai value => akamai(value),
            _ => throw new ImageKitInvalidDataException(
                "Data did not match any variant of UrlEndpointResponseUrlRewriter"
            ),
        };
    }

    public static implicit operator UrlEndpointResponseUrlRewriter(
        UrlEndpointResponseUrlRewriterCloudinary value
    ) => new(value);

    public static implicit operator UrlEndpointResponseUrlRewriter(
        UrlEndpointResponseUrlRewriterImgix value
    ) => new(value);

    public static implicit operator UrlEndpointResponseUrlRewriter(
        UrlEndpointResponseUrlRewriterAkamai value
    ) => new(value);

    /// <summary>
    /// Validates that the instance was constructed with a known variant and that this variant is valid
    /// (based on its own <c>Validate</c> method).
    ///
    /// <para>This is useful for instances constructed from raw JSON data (e.g. deserialized from an API response).</para>
    ///
    /// <exception cref="ImageKitInvalidDataException">
    /// Thrown when the instance does not pass validation.
    /// </exception>
    /// </summary>
    public override void Validate()
    {
        if (this.Value == null)
        {
            throw new ImageKitInvalidDataException(
                "Data did not match any variant of UrlEndpointResponseUrlRewriter"
            );
        }
        this.Switch(
            (cloudinary) => cloudinary.Validate(),
            (imgix) => imgix.Validate(),
            (akamai) => akamai.Validate()
        );
    }

    public virtual bool Equals(UrlEndpointResponseUrlRewriter? other) =>
        other != null
        && this.VariantIndex() == other.VariantIndex()
        && JsonElement.DeepEquals(this.Json, other.Json);

    public override int GetHashCode()
    {
        return 0;
    }

    public override string ToString() =>
        JsonSerializer.Serialize(
            FriendlyJsonPrinter.PrintValue(this.Json),
            ModelBase.ToStringSerializerOptions
        );

    int VariantIndex()
    {
        return this.Value switch
        {
            UrlEndpointResponseUrlRewriterCloudinary _ => 0,
            UrlEndpointResponseUrlRewriterImgix _ => 1,
            UrlEndpointResponseUrlRewriterAkamai _ => 2,
            _ => -1,
        };
    }
}

sealed class UrlEndpointResponseUrlRewriterConverter : JsonConverter<UrlEndpointResponseUrlRewriter>
{
    public override UrlEndpointResponseUrlRewriter? Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        var element = JsonSerializer.Deserialize<JsonElement>(ref reader, options);
        string? type;
        try
        {
            type = element.GetProperty("type").GetString();
        }
        catch
        {
            type = null;
        }

        switch (type)
        {
            case "CLOUDINARY":
            {
                try
                {
                    var deserialized =
                        JsonSerializer.Deserialize<UrlEndpointResponseUrlRewriterCloudinary>(
                            element,
                            options
                        );
                    if (deserialized != null)
                    {
                        return new(deserialized, element);
                    }
                }
                catch (JsonException)
                {
                    // ignore
                }

                return new(element);
            }
            case "IMGIX":
            {
                try
                {
                    var deserialized =
                        JsonSerializer.Deserialize<UrlEndpointResponseUrlRewriterImgix>(
                            element,
                            options
                        );
                    if (deserialized != null)
                    {
                        return new(deserialized, element);
                    }
                }
                catch (JsonException)
                {
                    // ignore
                }

                return new(element);
            }
            case "AKAMAI":
            {
                try
                {
                    var deserialized =
                        JsonSerializer.Deserialize<UrlEndpointResponseUrlRewriterAkamai>(
                            element,
                            options
                        );
                    if (deserialized != null)
                    {
                        return new(deserialized, element);
                    }
                }
                catch (JsonException)
                {
                    // ignore
                }

                return new(element);
            }
            default:
            {
                return new UrlEndpointResponseUrlRewriter(element);
            }
        }
    }

    public override void Write(
        Utf8JsonWriter writer,
        UrlEndpointResponseUrlRewriter value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(writer, value.Json, options);
    }
}

[JsonConverter(
    typeof(JsonModelConverter<
        UrlEndpointResponseUrlRewriterCloudinary,
        UrlEndpointResponseUrlRewriterCloudinaryFromRaw
    >)
)]
public sealed record class UrlEndpointResponseUrlRewriterCloudinary : JsonModel
{
    /// <summary>
    /// Whether to preserve `&lt;asset_type&gt;/&lt;delivery_type&gt;` in the rewritten URL.
    /// </summary>
    public required bool PreserveAssetDeliveryTypes
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<bool>("preserveAssetDeliveryTypes");
        }
        init { this._rawData.Set("preserveAssetDeliveryTypes", value); }
    }

    public JsonElement Type
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<JsonElement>("type");
        }
        init { this._rawData.Set("type", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.PreserveAssetDeliveryTypes;
        if (!JsonElement.DeepEquals(this.Type, JsonSerializer.SerializeToElement("CLOUDINARY")))
        {
            throw new ImageKitInvalidDataException("Invalid value given for constant");
        }
    }

    public UrlEndpointResponseUrlRewriterCloudinary()
    {
        this.Type = JsonSerializer.SerializeToElement("CLOUDINARY");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public UrlEndpointResponseUrlRewriterCloudinary(
        UrlEndpointResponseUrlRewriterCloudinary urlEndpointResponseUrlRewriterCloudinary
    )
        : base(urlEndpointResponseUrlRewriterCloudinary) { }
#pragma warning restore CS8618

    public UrlEndpointResponseUrlRewriterCloudinary(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        this._rawData = new(rawData);

        this.Type = JsonSerializer.SerializeToElement("CLOUDINARY");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    UrlEndpointResponseUrlRewriterCloudinary(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="UrlEndpointResponseUrlRewriterCloudinaryFromRaw.FromRawUnchecked"/>
    public static UrlEndpointResponseUrlRewriterCloudinary FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }

    [SetsRequiredMembers]
    public UrlEndpointResponseUrlRewriterCloudinary(bool preserveAssetDeliveryTypes)
        : this()
    {
        this.PreserveAssetDeliveryTypes = preserveAssetDeliveryTypes;
    }
}

class UrlEndpointResponseUrlRewriterCloudinaryFromRaw
    : IFromRawJson<UrlEndpointResponseUrlRewriterCloudinary>
{
    /// <inheritdoc/>
    public UrlEndpointResponseUrlRewriterCloudinary FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => UrlEndpointResponseUrlRewriterCloudinary.FromRawUnchecked(rawData);
}

[JsonConverter(typeof(UrlEndpointResponseUrlRewriterImgixConverter))]
public record class UrlEndpointResponseUrlRewriterImgix
{
    public JsonElement Element { get; private init; }

    public UrlEndpointResponseUrlRewriterImgix()
    {
        Element = JsonSerializer.Deserialize<JsonElement>(
            """
            {
              "type": "IMGIX"
            }
            """
        );
    }

    internal UrlEndpointResponseUrlRewriterImgix(JsonElement element)
    {
        Element = element;
    }

    /// <summary>
    /// Validates that the instance's underlying value is the expected constant.
    ///
    /// <para>This is useful for instances constructed from raw JSON data (e.g. deserialized from an API response).</para>
    ///
    /// <exception cref="ImageKitInvalidDataException">
    /// Thrown when the instance does not pass validation.
    /// </exception>
    /// </summary>
    public void Validate()
    {
        if (this != new UrlEndpointResponseUrlRewriterImgix())
        {
            throw new ImageKitInvalidDataException(
                "Invalid value given for 'UrlEndpointResponseUrlRewriterImgix'"
            );
        }
    }

    public override int GetHashCode()
    {
        return 0;
    }

    public virtual bool Equals(UrlEndpointResponseUrlRewriterImgix? other)
    {
        if (other == null)
        {
            return false;
        }

        return JsonElement.DeepEquals(this.Element, other.Element);
    }
}

class UrlEndpointResponseUrlRewriterImgixConverter
    : JsonConverter<UrlEndpointResponseUrlRewriterImgix>
{
    public override UrlEndpointResponseUrlRewriterImgix? Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return new(JsonSerializer.Deserialize<JsonElement>(ref reader, options));
    }

    public override void Write(
        Utf8JsonWriter writer,
        UrlEndpointResponseUrlRewriterImgix value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(writer, value.Element, options);
    }
}

[JsonConverter(typeof(UrlEndpointResponseUrlRewriterAkamaiConverter))]
public record class UrlEndpointResponseUrlRewriterAkamai
{
    public JsonElement Element { get; private init; }

    public UrlEndpointResponseUrlRewriterAkamai()
    {
        Element = JsonSerializer.Deserialize<JsonElement>(
            """
            {
              "type": "AKAMAI"
            }
            """
        );
    }

    internal UrlEndpointResponseUrlRewriterAkamai(JsonElement element)
    {
        Element = element;
    }

    /// <summary>
    /// Validates that the instance's underlying value is the expected constant.
    ///
    /// <para>This is useful for instances constructed from raw JSON data (e.g. deserialized from an API response).</para>
    ///
    /// <exception cref="ImageKitInvalidDataException">
    /// Thrown when the instance does not pass validation.
    /// </exception>
    /// </summary>
    public void Validate()
    {
        if (this != new UrlEndpointResponseUrlRewriterAkamai())
        {
            throw new ImageKitInvalidDataException(
                "Invalid value given for 'UrlEndpointResponseUrlRewriterAkamai'"
            );
        }
    }

    public override int GetHashCode()
    {
        return 0;
    }

    public virtual bool Equals(UrlEndpointResponseUrlRewriterAkamai? other)
    {
        if (other == null)
        {
            return false;
        }

        return JsonElement.DeepEquals(this.Element, other.Element);
    }
}

class UrlEndpointResponseUrlRewriterAkamaiConverter
    : JsonConverter<UrlEndpointResponseUrlRewriterAkamai>
{
    public override UrlEndpointResponseUrlRewriterAkamai? Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return new(JsonSerializer.Deserialize<JsonElement>(ref reader, options));
    }

    public override void Write(
        Utf8JsonWriter writer,
        UrlEndpointResponseUrlRewriterAkamai value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(writer, value.Element, options);
    }
}
