using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Imagekit.Models.Accounts.URLEndpoints.URLEndpointResponseProperties;

namespace Imagekit.Models.Accounts.URLEndpoints;

/// <summary>
/// URL‑endpoint object as returned by the API.
/// </summary>
[JsonConverter(typeof(ModelConverter<URLEndpointResponse>))]
public sealed record class URLEndpointResponse : ModelBase, IFromRaw<URLEndpointResponse>
{
    /// <summary>
    /// Unique identifier for the URL-endpoint. This is generated by ImageKit when
    /// you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.
    /// </summary>
    public required string ID
    {
        get
        {
            if (!this.Properties.TryGetValue("id", out JsonElement element))
                throw new ArgumentOutOfRangeException("id", "Missing required argument");

            return JsonSerializer.Deserialize<string>(element, ModelBase.SerializerOptions)
                ?? throw new ArgumentNullException("id");
        }
        set
        {
            this.Properties["id"] = JsonSerializer.SerializeToElement(
                value,
                ModelBase.SerializerOptions
            );
        }
    }

    /// <summary>
    /// Description of the URL endpoint.
    /// </summary>
    public required string Description
    {
        get
        {
            if (!this.Properties.TryGetValue("description", out JsonElement element))
                throw new ArgumentOutOfRangeException("description", "Missing required argument");

            return JsonSerializer.Deserialize<string>(element, ModelBase.SerializerOptions)
                ?? throw new ArgumentNullException("description");
        }
        set
        {
            this.Properties["description"] = JsonSerializer.SerializeToElement(
                value,
                ModelBase.SerializerOptions
            );
        }
    }

    /// <summary>
    /// Ordered list of origin IDs to try when the file isn’t in the Media Library;
    /// ImageKit checks them in the sequence provided. Origin must be created before
    /// it can be used in a URL endpoint.
    /// </summary>
    public required List<string> Origins
    {
        get
        {
            if (!this.Properties.TryGetValue("origins", out JsonElement element))
                throw new ArgumentOutOfRangeException("origins", "Missing required argument");

            return JsonSerializer.Deserialize<List<string>>(element, ModelBase.SerializerOptions)
                ?? throw new ArgumentNullException("origins");
        }
        set
        {
            this.Properties["origins"] = JsonSerializer.SerializeToElement(
                value,
                ModelBase.SerializerOptions
            );
        }
    }

    /// <summary>
    /// Path segment appended to your base URL to form the endpoint (letters, digits,
    /// and hyphens only — or empty for the default endpoint).
    /// </summary>
    public required string URLPrefix
    {
        get
        {
            if (!this.Properties.TryGetValue("urlPrefix", out JsonElement element))
                throw new ArgumentOutOfRangeException("urlPrefix", "Missing required argument");

            return JsonSerializer.Deserialize<string>(element, ModelBase.SerializerOptions)
                ?? throw new ArgumentNullException("urlPrefix");
        }
        set
        {
            this.Properties["urlPrefix"] = JsonSerializer.SerializeToElement(
                value,
                ModelBase.SerializerOptions
            );
        }
    }

    /// <summary>
    /// Configuration for third-party URL rewriting.
    /// </summary>
    public URLRewriter? URLRewriter
    {
        get
        {
            if (!this.Properties.TryGetValue("urlRewriter", out JsonElement element))
                return null;

            return JsonSerializer.Deserialize<URLRewriter?>(element, ModelBase.SerializerOptions);
        }
        set
        {
            this.Properties["urlRewriter"] = JsonSerializer.SerializeToElement(
                value,
                ModelBase.SerializerOptions
            );
        }
    }

    public override void Validate()
    {
        _ = this.ID;
        _ = this.Description;
        _ = this.Origins;
        _ = this.URLPrefix;
        this.URLRewriter?.Validate();
    }

    public URLEndpointResponse() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    URLEndpointResponse(Dictionary<string, JsonElement> properties)
    {
        Properties = properties;
    }
#pragma warning restore CS8618

    public static URLEndpointResponse FromRawUnchecked(Dictionary<string, JsonElement> properties)
    {
        return new(properties);
    }
}
