using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using ImagekitDiversion.Core;
using ImagekitDiversion.Exceptions;

namespace ImagekitDiversion.Models.Accounts.UrlEndpoints;

/// <summary>
/// URL‑endpoint object as returned by the API.
/// </summary>
[JsonConverter(typeof(JsonModelConverter<UrlEndpoint, UrlEndpointFromRaw>))]
public sealed record class UrlEndpoint : JsonModel
{
    /// <summary>
    /// Unique identifier for the URL-endpoint. This is generated by ImageKit when
    /// you create a new URL-endpoint. For the default URL-endpoint, this is always `default`.
    /// </summary>
    public required string ID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("id");
        }
        init { this._rawData.Set("id", value); }
    }

    /// <summary>
    /// Description of the URL endpoint.
    /// </summary>
    public required string Description
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("description");
        }
        init { this._rawData.Set("description", value); }
    }

    /// <summary>
    /// Ordered list of origin IDs to try when the file isn’t in the Media Library;
    /// ImageKit checks them in the sequence provided. Origin must be created before
    /// it can be used in a URL endpoint.
    /// </summary>
    public required IReadOnlyList<string> Origins
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<ImmutableArray<string>>("origins");
        }
        init
        {
            this._rawData.Set<ImmutableArray<string>>(
                "origins",
                ImmutableArray.ToImmutableArray(value)
            );
        }
    }

    /// <summary>
    /// Path segment appended to your base URL to form the endpoint (letters, digits,
    /// and hyphens only — or empty for the default endpoint).
    /// </summary>
    public required string UrlPrefix
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("urlPrefix");
        }
        init { this._rawData.Set("urlPrefix", value); }
    }

    /// <summary>
    /// Configuration for third-party URL rewriting.
    /// </summary>
    public UrlEndpointUrlRewriter? UrlRewriter
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<UrlEndpointUrlRewriter>("urlRewriter");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("urlRewriter", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.ID;
        _ = this.Description;
        _ = this.Origins;
        _ = this.UrlPrefix;
        this.UrlRewriter?.Validate();
    }

    public UrlEndpoint() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public UrlEndpoint(UrlEndpoint urlEndpoint)
        : base(urlEndpoint) { }
#pragma warning restore CS8618

    public UrlEndpoint(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    UrlEndpoint(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="UrlEndpointFromRaw.FromRawUnchecked"/>
    public static UrlEndpoint FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class UrlEndpointFromRaw : IFromRawJson<UrlEndpoint>
{
    /// <inheritdoc/>
    public UrlEndpoint FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        UrlEndpoint.FromRawUnchecked(rawData);
}

/// <summary>
/// Configuration for third-party URL rewriting.
/// </summary>
[JsonConverter(typeof(UrlEndpointUrlRewriterConverter))]
public record class UrlEndpointUrlRewriter : ModelBase
{
    public object? Value { get; } = null;

    JsonElement? _element = null;

    public JsonElement Json
    {
        get
        {
            return this._element ??= JsonSerializer.SerializeToElement(
                this.Value,
                ModelBase.SerializerOptions
            );
        }
    }

    public UrlEndpointUrlRewriter(
        UrlEndpointUrlRewriterCloudinary value,
        JsonElement? element = null
    )
    {
        this.Value = value;
        this._element = element;
    }

    public UrlEndpointUrlRewriter(UrlEndpointUrlRewriterImgix value, JsonElement? element = null)
    {
        this.Value = value;
        this._element = element;
    }

    public UrlEndpointUrlRewriter(UrlEndpointUrlRewriterAkamai value, JsonElement? element = null)
    {
        this.Value = value;
        this._element = element;
    }

    public UrlEndpointUrlRewriter(JsonElement element)
    {
        this._element = element;
    }

    /// <summary>
    /// Returns true and sets the <c>out</c> parameter if the instance was constructed with a variant of
    /// type <see cref="UrlEndpointUrlRewriterCloudinary"/>.
    ///
    /// <para>Consider using <see cref="Switch"/> or <see cref="Match"/> if you need to handle every variant.</para>
    ///
    /// <example>
    /// <code>
    /// if (instance.TryPickCloudinary(out var value)) {
    ///     // `value` is of type `UrlEndpointUrlRewriterCloudinary`
    ///     Console.WriteLine(value);
    /// }
    /// </code>
    /// </example>
    /// </summary>
    public bool TryPickCloudinary([NotNullWhen(true)] out UrlEndpointUrlRewriterCloudinary? value)
    {
        value = this.Value as UrlEndpointUrlRewriterCloudinary;
        return value != null;
    }

    /// <summary>
    /// Returns true and sets the <c>out</c> parameter if the instance was constructed with a variant of
    /// type <see cref="UrlEndpointUrlRewriterImgix"/>.
    ///
    /// <para>Consider using <see cref="Switch"/> or <see cref="Match"/> if you need to handle every variant.</para>
    ///
    /// <example>
    /// <code>
    /// if (instance.TryPickImgix(out var value)) {
    ///     // `value` is of type `UrlEndpointUrlRewriterImgix`
    ///     Console.WriteLine(value);
    /// }
    /// </code>
    /// </example>
    /// </summary>
    public bool TryPickImgix([NotNullWhen(true)] out UrlEndpointUrlRewriterImgix? value)
    {
        value = this.Value as UrlEndpointUrlRewriterImgix;
        return value != null;
    }

    /// <summary>
    /// Returns true and sets the <c>out</c> parameter if the instance was constructed with a variant of
    /// type <see cref="UrlEndpointUrlRewriterAkamai"/>.
    ///
    /// <para>Consider using <see cref="Switch"/> or <see cref="Match"/> if you need to handle every variant.</para>
    ///
    /// <example>
    /// <code>
    /// if (instance.TryPickAkamai(out var value)) {
    ///     // `value` is of type `UrlEndpointUrlRewriterAkamai`
    ///     Console.WriteLine(value);
    /// }
    /// </code>
    /// </example>
    /// </summary>
    public bool TryPickAkamai([NotNullWhen(true)] out UrlEndpointUrlRewriterAkamai? value)
    {
        value = this.Value as UrlEndpointUrlRewriterAkamai;
        return value != null;
    }

    /// <summary>
    /// Calls the function parameter corresponding to the variant the instance was constructed with.
    ///
    /// <para>Use the <c>TryPick</c> method(s) if you don't need to handle every variant, or <see cref="Match"/>
    /// if you need your function parameters to return something.</para>
    ///
    /// <exception cref="ImagekitDiversionInvalidDataException">
    /// Thrown when the instance was constructed with an unknown variant (e.g. deserialized from raw data
    /// that doesn't match any variant's expected shape).
    /// </exception>
    ///
    /// <example>
    /// <code>
    /// instance.Switch(
    ///     (UrlEndpointUrlRewriterCloudinary value) =&gt; {...},
    ///     (UrlEndpointUrlRewriterImgix value) =&gt; {...},
    ///     (UrlEndpointUrlRewriterAkamai value) =&gt; {...}
    /// );
    /// </code>
    /// </example>
    /// </summary>
    public void Switch(
        Action<UrlEndpointUrlRewriterCloudinary> cloudinary,
        Action<UrlEndpointUrlRewriterImgix> imgix,
        Action<UrlEndpointUrlRewriterAkamai> akamai
    )
    {
        switch (this.Value)
        {
            case UrlEndpointUrlRewriterCloudinary value:
                cloudinary(value);
                break;
            case UrlEndpointUrlRewriterImgix value:
                imgix(value);
                break;
            case UrlEndpointUrlRewriterAkamai value:
                akamai(value);
                break;
            default:
                throw new ImagekitDiversionInvalidDataException(
                    "Data did not match any variant of UrlEndpointUrlRewriter"
                );
        }
    }

    /// <summary>
    /// Calls the function parameter corresponding to the variant the instance was constructed with and
    /// returns its result.
    ///
    /// <para>Use the <c>TryPick</c> method(s) if you don't need to handle every variant, or <see cref="Switch"/>
    /// if you don't need your function parameters to return a value.</para>
    ///
    /// <exception cref="ImagekitDiversionInvalidDataException">
    /// Thrown when the instance was constructed with an unknown variant (e.g. deserialized from raw data
    /// that doesn't match any variant's expected shape).
    /// </exception>
    ///
    /// <example>
    /// <code>
    /// var result = instance.Match(
    ///     (UrlEndpointUrlRewriterCloudinary value) =&gt; {...},
    ///     (UrlEndpointUrlRewriterImgix value) =&gt; {...},
    ///     (UrlEndpointUrlRewriterAkamai value) =&gt; {...}
    /// );
    /// </code>
    /// </example>
    /// </summary>
    public T Match<T>(
        Func<UrlEndpointUrlRewriterCloudinary, T> cloudinary,
        Func<UrlEndpointUrlRewriterImgix, T> imgix,
        Func<UrlEndpointUrlRewriterAkamai, T> akamai
    )
    {
        return this.Value switch
        {
            UrlEndpointUrlRewriterCloudinary value => cloudinary(value),
            UrlEndpointUrlRewriterImgix value => imgix(value),
            UrlEndpointUrlRewriterAkamai value => akamai(value),
            _ => throw new ImagekitDiversionInvalidDataException(
                "Data did not match any variant of UrlEndpointUrlRewriter"
            ),
        };
    }

    public static implicit operator UrlEndpointUrlRewriter(
        UrlEndpointUrlRewriterCloudinary value
    ) => new(value);

    public static implicit operator UrlEndpointUrlRewriter(UrlEndpointUrlRewriterImgix value) =>
        new(value);

    public static implicit operator UrlEndpointUrlRewriter(UrlEndpointUrlRewriterAkamai value) =>
        new(value);

    /// <summary>
    /// Validates that the instance was constructed with a known variant and that this variant is valid
    /// (based on its own <c>Validate</c> method).
    ///
    /// <para>This is useful for instances constructed from raw JSON data (e.g. deserialized from an API response).</para>
    ///
    /// <exception cref="ImagekitDiversionInvalidDataException">
    /// Thrown when the instance does not pass validation.
    /// </exception>
    /// </summary>
    public override void Validate()
    {
        if (this.Value == null)
        {
            throw new ImagekitDiversionInvalidDataException(
                "Data did not match any variant of UrlEndpointUrlRewriter"
            );
        }
        this.Switch(
            (cloudinary) => cloudinary.Validate(),
            (imgix) => imgix.Validate(),
            (akamai) => akamai.Validate()
        );
    }

    public virtual bool Equals(UrlEndpointUrlRewriter? other) =>
        other != null
        && this.VariantIndex() == other.VariantIndex()
        && JsonElement.DeepEquals(this.Json, other.Json);

    public override int GetHashCode()
    {
        return 0;
    }

    public override string ToString() =>
        JsonSerializer.Serialize(
            FriendlyJsonPrinter.PrintValue(this.Json),
            ModelBase.ToStringSerializerOptions
        );

    int VariantIndex()
    {
        return this.Value switch
        {
            UrlEndpointUrlRewriterCloudinary _ => 0,
            UrlEndpointUrlRewriterImgix _ => 1,
            UrlEndpointUrlRewriterAkamai _ => 2,
            _ => -1,
        };
    }
}

sealed class UrlEndpointUrlRewriterConverter : JsonConverter<UrlEndpointUrlRewriter>
{
    public override UrlEndpointUrlRewriter? Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        var element = JsonSerializer.Deserialize<JsonElement>(ref reader, options);
        string? type;
        try
        {
            type = element.GetProperty("type").GetString();
        }
        catch
        {
            type = null;
        }

        switch (type)
        {
            case "CLOUDINARY":
            {
                try
                {
                    var deserialized = JsonSerializer.Deserialize<UrlEndpointUrlRewriterCloudinary>(
                        element,
                        options
                    );
                    if (deserialized != null)
                    {
                        return new(deserialized, element);
                    }
                }
                catch (JsonException)
                {
                    // ignore
                }

                return new(element);
            }
            case "IMGIX":
            {
                try
                {
                    var deserialized = JsonSerializer.Deserialize<UrlEndpointUrlRewriterImgix>(
                        element,
                        options
                    );
                    if (deserialized != null)
                    {
                        return new(deserialized, element);
                    }
                }
                catch (JsonException)
                {
                    // ignore
                }

                return new(element);
            }
            case "AKAMAI":
            {
                try
                {
                    var deserialized = JsonSerializer.Deserialize<UrlEndpointUrlRewriterAkamai>(
                        element,
                        options
                    );
                    if (deserialized != null)
                    {
                        return new(deserialized, element);
                    }
                }
                catch (JsonException)
                {
                    // ignore
                }

                return new(element);
            }
            default:
            {
                return new UrlEndpointUrlRewriter(element);
            }
        }
    }

    public override void Write(
        Utf8JsonWriter writer,
        UrlEndpointUrlRewriter value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(writer, value.Json, options);
    }
}

[JsonConverter(
    typeof(JsonModelConverter<
        UrlEndpointUrlRewriterCloudinary,
        UrlEndpointUrlRewriterCloudinaryFromRaw
    >)
)]
public sealed record class UrlEndpointUrlRewriterCloudinary : JsonModel
{
    /// <summary>
    /// Whether to preserve `&lt;asset_type&gt;/&lt;delivery_type&gt;` in the rewritten URL.
    /// </summary>
    public required bool PreserveAssetDeliveryTypes
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<bool>("preserveAssetDeliveryTypes");
        }
        init { this._rawData.Set("preserveAssetDeliveryTypes", value); }
    }

    public JsonElement Type
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<JsonElement>("type");
        }
        init { this._rawData.Set("type", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.PreserveAssetDeliveryTypes;
        if (!JsonElement.DeepEquals(this.Type, JsonSerializer.SerializeToElement("CLOUDINARY")))
        {
            throw new ImagekitDiversionInvalidDataException("Invalid value given for constant");
        }
    }

    public UrlEndpointUrlRewriterCloudinary()
    {
        this.Type = JsonSerializer.SerializeToElement("CLOUDINARY");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public UrlEndpointUrlRewriterCloudinary(
        UrlEndpointUrlRewriterCloudinary urlEndpointUrlRewriterCloudinary
    )
        : base(urlEndpointUrlRewriterCloudinary) { }
#pragma warning restore CS8618

    public UrlEndpointUrlRewriterCloudinary(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);

        this.Type = JsonSerializer.SerializeToElement("CLOUDINARY");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    UrlEndpointUrlRewriterCloudinary(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="UrlEndpointUrlRewriterCloudinaryFromRaw.FromRawUnchecked"/>
    public static UrlEndpointUrlRewriterCloudinary FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }

    [SetsRequiredMembers]
    public UrlEndpointUrlRewriterCloudinary(bool preserveAssetDeliveryTypes)
        : this()
    {
        this.PreserveAssetDeliveryTypes = preserveAssetDeliveryTypes;
    }
}

class UrlEndpointUrlRewriterCloudinaryFromRaw : IFromRawJson<UrlEndpointUrlRewriterCloudinary>
{
    /// <inheritdoc/>
    public UrlEndpointUrlRewriterCloudinary FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    ) => UrlEndpointUrlRewriterCloudinary.FromRawUnchecked(rawData);
}

[JsonConverter(typeof(UrlEndpointUrlRewriterImgixConverter))]
public record class UrlEndpointUrlRewriterImgix
{
    public JsonElement Element { get; private init; }

    public UrlEndpointUrlRewriterImgix()
    {
        Element = JsonSerializer.Deserialize<JsonElement>(
            """
            {
              "type": "IMGIX"
            }
            """
        );
    }

    internal UrlEndpointUrlRewriterImgix(JsonElement element)
    {
        Element = element;
    }

    /// <summary>
    /// Validates that the instance's underlying value is the expected constant.
    ///
    /// <para>This is useful for instances constructed from raw JSON data (e.g. deserialized from an API response).</para>
    ///
    /// <exception cref="ImagekitDiversionInvalidDataException">
    /// Thrown when the instance does not pass validation.
    /// </exception>
    /// </summary>
    public void Validate()
    {
        if (this != new UrlEndpointUrlRewriterImgix())
        {
            throw new ImagekitDiversionInvalidDataException(
                "Invalid value given for 'UrlEndpointUrlRewriterImgix'"
            );
        }
    }

    public override int GetHashCode()
    {
        return 0;
    }

    public virtual bool Equals(UrlEndpointUrlRewriterImgix? other)
    {
        if (other == null)
        {
            return false;
        }

        return JsonElement.DeepEquals(this.Element, other.Element);
    }
}

class UrlEndpointUrlRewriterImgixConverter : JsonConverter<UrlEndpointUrlRewriterImgix>
{
    public override UrlEndpointUrlRewriterImgix? Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return new(JsonSerializer.Deserialize<JsonElement>(ref reader, options));
    }

    public override void Write(
        Utf8JsonWriter writer,
        UrlEndpointUrlRewriterImgix value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(writer, value.Element, options);
    }
}

[JsonConverter(typeof(UrlEndpointUrlRewriterAkamaiConverter))]
public record class UrlEndpointUrlRewriterAkamai
{
    public JsonElement Element { get; private init; }

    public UrlEndpointUrlRewriterAkamai()
    {
        Element = JsonSerializer.Deserialize<JsonElement>(
            """
            {
              "type": "AKAMAI"
            }
            """
        );
    }

    internal UrlEndpointUrlRewriterAkamai(JsonElement element)
    {
        Element = element;
    }

    /// <summary>
    /// Validates that the instance's underlying value is the expected constant.
    ///
    /// <para>This is useful for instances constructed from raw JSON data (e.g. deserialized from an API response).</para>
    ///
    /// <exception cref="ImagekitDiversionInvalidDataException">
    /// Thrown when the instance does not pass validation.
    /// </exception>
    /// </summary>
    public void Validate()
    {
        if (this != new UrlEndpointUrlRewriterAkamai())
        {
            throw new ImagekitDiversionInvalidDataException(
                "Invalid value given for 'UrlEndpointUrlRewriterAkamai'"
            );
        }
    }

    public override int GetHashCode()
    {
        return 0;
    }

    public virtual bool Equals(UrlEndpointUrlRewriterAkamai? other)
    {
        if (other == null)
        {
            return false;
        }

        return JsonElement.DeepEquals(this.Element, other.Element);
    }
}

class UrlEndpointUrlRewriterAkamaiConverter : JsonConverter<UrlEndpointUrlRewriterAkamai>
{
    public override UrlEndpointUrlRewriterAkamai? Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return new(JsonSerializer.Deserialize<JsonElement>(ref reader, options));
    }

    public override void Write(
        Utf8JsonWriter writer,
        UrlEndpointUrlRewriterAkamai value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(writer, value.Element, options);
    }
}
