// <copyright file="GlobalSuppressions.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "not needed", Scope = "member", Target = "~F:Imagekit.Models.DeleteFileVersionRequest.fileId")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "not needed", Scope = "member", Target = "~M:Imagekit.Sdk.RestClient.MoveFile(MoveFileRequest)~ResponseMetaData")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "not needed", Scope = "member", Target = "~M:Imagekit.Imagekit.#ctor(System.String,System.String,System.String,System.String)")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1601:Partial elements should be documented", Justification = "not needed", Scope = "type", Target = "~T:Imagekit.BaseImagekit`1")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "not needed", Scope = "type", Target = "~T:ImagekitSample.Program")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1117:Parameters should be on same line or separate lines", Justification = "not needed", Scope = "member", Target = "~M:Imagekit.Sdk.RestClient.PurgeCacheAsync(System.String)~System.Threading.Tasks.Task{ResponseMetaData}")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1117:Parameters should be on same line or separate lines", Justification = "not needed", Scope = "member", Target = "~M:Imagekit.Sdk.RestClient.DeleteFileVersion(Imagekit.Models.DeleteFileVersionRequest)~ResponseMetaData")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "not needed", Scope = "type", Target = "~T:Imagekit.Helper.QueryMaker")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "not needed", Scope = "member", Target = "~M:Imagekit.Sdk.ImagekitClient.GetRemoteFileMetadata(System.String)~ResponseMetaData")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1117:Parameters should be on same line or separate lines", Justification = "not needed", Scope = "member", Target = "~M:Imagekit.Sdk.RestClient.DeleteFileVersionAsync(Imagekit.Models.DeleteFileVersionRequest)~System.Threading.Tasks.Task{ResponseMetaData}")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "not needed", Scope = "member", Target = "~M:Imagekit.Sdk.RestClient.PurgeStatus(System.String)~ResponseMetaData")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "not needed", Scope = "member", Target = "~F:Imagekit.BaseImagekit`1.options")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "not needed", Scope = "member", Target = "~F:Transformation.nestedTransforms")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "not needed", Scope = "member", Target = "~F:Transformation.transformParams")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private", Justification = "not needed", Scope = "member", Target = "~F:Url.options")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "not needed", Scope = "member", Target = "~F:Transformation.transformParams")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "not needed", Scope = "member", Target = "~M:Imagekit.Sdk.ImagekitClient.#ctor(System.String,System.String,System.String)")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1201:Elements should appear in the correct order", Justification = "not needed", Scope = "member", Target = "~M:Transformation.#ctor")]
[assembly: SuppressMessage("Compiler", "CS0108:Member hides inherited member; missing new keyword", Justification = "not needed", Scope = "member", Target = "~P:Imagekit.Models.Response.ResultMetaData.Raw")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "not needed", Scope = "member", Target = "~P:ResultCache.Help")]
[assembly: SuppressMessage("Compiler", "CS0108:Member hides inherited member; missing new keyword", Justification = "not needed", Scope = "member", Target = "~P:ResultCache.Raw")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "not needed", Scope = "member", Target = "~P:ResultCache.Raw")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "not needed", Scope = "member", Target = "~P:ResultCache.RequestId")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "not needed", Scope = "member", Target = "~P:ResultCacheStatus.Help")]
[assembly: SuppressMessage("Compiler", "CS0108:Member hides inherited member; missing new keyword", Justification = "not needed", Scope = "member", Target = "~P:ResultCacheStatus.Raw")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "not needed", Scope = "member", Target = "~P:ResultCacheStatus.Raw")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "not needed", Scope = "member", Target = "~P:ResultCacheStatus.Status")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "not needed", Scope = "member", Target = "~P:ResultCustomMetaDataField.Id")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "not needed", Scope = "member", Target = "~P:ResultCustomMetaDataField.Label")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "not needed", Scope = "member", Target = "~P:ResultCustomMetaDataField.Message")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "not needed", Scope = "member", Target = "~P:ResultCustomMetaDataField.Name")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "not needed", Scope = "member", Target = "~P:ResultCustomMetaDataField.Schema")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "not needed", Scope = "member", Target = "~P:ResultException.Help")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "not needed", Scope = "member", Target = "~P:ResultException.Message")]
[assembly: SuppressMessage("Compiler", "CS0108:Member hides inherited member; missing new keyword", Justification = "not needed", Scope = "member", Target = "~P:ResultFileDelete.Raw")]
[assembly: SuppressMessage("Compiler", "CS0108:Member hides inherited member; missing new keyword", Justification = "not needed", Scope = "member", Target = "~P:ResultList.Raw")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members", Justification = "not needed", Scope = "member", Target = "~P:ResultNoContent.ResponseMetaData")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "not needed", Scope = "member", Target = "~M:Imagekit.Helper.GetJsonBody.GetBase64(System.Byte[])~System.String")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1202:Elements should be ordered by access", Justification = "not needed", Scope = "member", Target = "~M:Transformation.ToString~System.String")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1123:Do not place regions within elements", Justification = "not needed", Scope = "member", Target = "~M:ImagekitSample.Program.Main(System.String[])")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1400:Access modifier should be declared", Justification = "not needed", Scope = "member", Target = "~M:ImagekitSample.Program.Main(System.String[])")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1649:File name should match first type name", Justification = "not needed", Scope = "type", Target = "~T:Imagekit.Sdk.ImagekitClient")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules", "SA1204:Static elements should appear before instance elements", Justification = "not needed", Scope = "member", Target = "~M:Transformation.ToString(System.Object)~System.String")]
