using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Imagekit.Models.Accounts.Origins.OriginResponseProperties;

[JsonConverter(typeof(ModelConverter<S3Compatible>))]
public sealed record class S3Compatible : ModelBase, IFromRaw<S3Compatible>
{
    /// <summary>
    /// Unique identifier for the origin. This is generated by ImageKit when you create
    /// a new origin.
    /// </summary>
    public required string ID
    {
        get
        {
            if (!this.Properties.TryGetValue("id", out JsonElement element))
                throw new ArgumentOutOfRangeException("id", "Missing required argument");

            return JsonSerializer.Deserialize<string>(element, ModelBase.SerializerOptions)
                ?? throw new ArgumentNullException("id");
        }
        set
        {
            this.Properties["id"] = JsonSerializer.SerializeToElement(
                value,
                ModelBase.SerializerOptions
            );
        }
    }

    /// <summary>
    /// S3 bucket name.
    /// </summary>
    public required string Bucket
    {
        get
        {
            if (!this.Properties.TryGetValue("bucket", out JsonElement element))
                throw new ArgumentOutOfRangeException("bucket", "Missing required argument");

            return JsonSerializer.Deserialize<string>(element, ModelBase.SerializerOptions)
                ?? throw new ArgumentNullException("bucket");
        }
        set
        {
            this.Properties["bucket"] = JsonSerializer.SerializeToElement(
                value,
                ModelBase.SerializerOptions
            );
        }
    }

    /// <summary>
    /// Custom S3-compatible endpoint.
    /// </summary>
    public required string Endpoint
    {
        get
        {
            if (!this.Properties.TryGetValue("endpoint", out JsonElement element))
                throw new ArgumentOutOfRangeException("endpoint", "Missing required argument");

            return JsonSerializer.Deserialize<string>(element, ModelBase.SerializerOptions)
                ?? throw new ArgumentNullException("endpoint");
        }
        set
        {
            this.Properties["endpoint"] = JsonSerializer.SerializeToElement(
                value,
                ModelBase.SerializerOptions
            );
        }
    }

    /// <summary>
    /// Whether to send a Canonical header.
    /// </summary>
    public required bool IncludeCanonicalHeader
    {
        get
        {
            if (!this.Properties.TryGetValue("includeCanonicalHeader", out JsonElement element))
                throw new ArgumentOutOfRangeException(
                    "includeCanonicalHeader",
                    "Missing required argument"
                );

            return JsonSerializer.Deserialize<bool>(element, ModelBase.SerializerOptions);
        }
        set
        {
            this.Properties["includeCanonicalHeader"] = JsonSerializer.SerializeToElement(
                value,
                ModelBase.SerializerOptions
            );
        }
    }

    /// <summary>
    /// Display name of the origin.
    /// </summary>
    public required string Name
    {
        get
        {
            if (!this.Properties.TryGetValue("name", out JsonElement element))
                throw new ArgumentOutOfRangeException("name", "Missing required argument");

            return JsonSerializer.Deserialize<string>(element, ModelBase.SerializerOptions)
                ?? throw new ArgumentNullException("name");
        }
        set
        {
            this.Properties["name"] = JsonSerializer.SerializeToElement(
                value,
                ModelBase.SerializerOptions
            );
        }
    }

    /// <summary>
    /// Path prefix inside the bucket.
    /// </summary>
    public required string Prefix
    {
        get
        {
            if (!this.Properties.TryGetValue("prefix", out JsonElement element))
                throw new ArgumentOutOfRangeException("prefix", "Missing required argument");

            return JsonSerializer.Deserialize<string>(element, ModelBase.SerializerOptions)
                ?? throw new ArgumentNullException("prefix");
        }
        set
        {
            this.Properties["prefix"] = JsonSerializer.SerializeToElement(
                value,
                ModelBase.SerializerOptions
            );
        }
    }

    /// <summary>
    /// Use path-style S3 URLs?
    /// </summary>
    public required bool S3ForcePathStyle
    {
        get
        {
            if (!this.Properties.TryGetValue("s3ForcePathStyle", out JsonElement element))
                throw new ArgumentOutOfRangeException(
                    "s3ForcePathStyle",
                    "Missing required argument"
                );

            return JsonSerializer.Deserialize<bool>(element, ModelBase.SerializerOptions);
        }
        set
        {
            this.Properties["s3ForcePathStyle"] = JsonSerializer.SerializeToElement(
                value,
                ModelBase.SerializerOptions
            );
        }
    }

    public JsonElement Type
    {
        get
        {
            if (!this.Properties.TryGetValue("type", out JsonElement element))
                throw new ArgumentOutOfRangeException("type", "Missing required argument");

            return JsonSerializer.Deserialize<JsonElement>(element, ModelBase.SerializerOptions);
        }
        set
        {
            this.Properties["type"] = JsonSerializer.SerializeToElement(
                value,
                ModelBase.SerializerOptions
            );
        }
    }

    /// <summary>
    /// URL used in the Canonical header (if enabled).
    /// </summary>
    public string? BaseURLForCanonicalHeader
    {
        get
        {
            if (!this.Properties.TryGetValue("baseUrlForCanonicalHeader", out JsonElement element))
                return null;

            return JsonSerializer.Deserialize<string?>(element, ModelBase.SerializerOptions);
        }
        set
        {
            this.Properties["baseUrlForCanonicalHeader"] = JsonSerializer.SerializeToElement(
                value,
                ModelBase.SerializerOptions
            );
        }
    }

    public override void Validate()
    {
        _ = this.ID;
        _ = this.Bucket;
        _ = this.Endpoint;
        _ = this.IncludeCanonicalHeader;
        _ = this.Name;
        _ = this.Prefix;
        _ = this.S3ForcePathStyle;
        _ = this.BaseURLForCanonicalHeader;
    }

    public S3Compatible()
    {
        this.Type = JsonSerializer.Deserialize<JsonElement>("\"S3_COMPATIBLE\"");
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    S3Compatible(Dictionary<string, JsonElement> properties)
    {
        Properties = properties;
    }
#pragma warning restore CS8618

    public static S3Compatible FromRawUnchecked(Dictionary<string, JsonElement> properties)
    {
        return new(properties);
    }
}
