#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

echo "==> Running dotnet csharpier check"
dotnet csharpier check .

echo "==> Running dotnet format"
dotnet format style --severity info --verify-no-changes
dotnet format analyzers --severity info --verify-no-changes
