using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Imagekit.Core;

namespace Imagekit.Models;

/// <summary>
/// A named transformation is an alias for a transformation string, letting you apply
/// and later update complex transformations without changing your image or video
/// URLs. Learn more about [named transformations](https://imagekit.io/docs/transformations#named-transformations).
/// </summary>
[JsonConverter(typeof(JsonModelConverter<NamedTransformation, NamedTransformationFromRaw>))]
public sealed record class NamedTransformation : JsonModel
{
    /// <summary>
    /// Unique identifier generated by ImageKit when the named transformation was created.
    /// </summary>
    public string? ID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("id");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("id", value);
        }
    }

    /// <summary>
    /// ISO 8601 timestamp of when the named transformation was created.
    /// </summary>
    public DateTimeOffset? CreatedAt
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<DateTimeOffset>("createdAt");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("createdAt", value);
        }
    }

    /// <summary>
    /// Whether the named transformation is currently enabled.
    /// </summary>
    public bool? Enabled
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<bool>("enabled");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("enabled", value);
        }
    }

    /// <summary>
    /// Name of the named transformation, used as `tr:n-&lt;name&gt;` in image and
    /// video URLs.
    /// </summary>
    public string? Name
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("name");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("name", value);
        }
    }

    /// <summary>
    /// Transformation string this name refers to. Always includes the `tr:` prefix,
    /// even if you omitted it in the request.
    /// </summary>
    public string? Transformation
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("transformation");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawData.Set("transformation", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.ID;
        _ = this.CreatedAt;
        _ = this.Enabled;
        _ = this.Name;
        _ = this.Transformation;
    }

    public NamedTransformation() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public NamedTransformation(NamedTransformation namedTransformation)
        : base(namedTransformation) { }
#pragma warning restore CS8618

    public NamedTransformation(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    NamedTransformation(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="NamedTransformationFromRaw.FromRawUnchecked"/>
    public static NamedTransformation FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class NamedTransformationFromRaw : IFromRawJson<NamedTransformation>
{
    /// <inheritdoc/>
    public NamedTransformation FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        NamedTransformation.FromRawUnchecked(rawData);
}
