using System.Collections.Generic;
using System.Threading.Tasks;
using Imagekit.Models.Accounts.URLEndpoints;

namespace Imagekit.Services.Accounts.URLEndpoints;

public interface IURLEndpointService
{
    /// <summary>
    /// **Note:** This API is currently in beta.   Creates a new URL‑endpoint and
    /// returns the resulting object.
    /// </summary>
    Task<URLEndpointResponse> Create(URLEndpointCreateParams parameters);

    /// <summary>
    /// **Note:** This API is currently in beta.   Updates the URL‑endpoint identified
    /// by `id` and returns the updated object.
    /// </summary>
    Task<URLEndpointResponse> Update(URLEndpointUpdateParams parameters);

    /// <summary>
    /// **Note:** This API is currently in beta.   Returns an array of all URL‑endpoints
    /// configured including the default URL-endpoint generated by ImageKit during
    /// account creation.
    /// </summary>
    Task<List<URLEndpointResponse>> List(URLEndpointListParams? parameters = null);

    /// <summary>
    /// **Note:** This API is currently in beta.   Deletes the URL‑endpoint identified
    /// by `id`. You cannot delete the default URL‑endpoint created by ImageKit during
    /// account creation.
    /// </summary>
    Task Delete(URLEndpointDeleteParams parameters);

    /// <summary>
    /// **Note:** This API is currently in beta.   Retrieves the URL‑endpoint identified
    /// by `id`.
    /// </summary>
    Task<URLEndpointResponse> Get(URLEndpointGetParams parameters);
}
