using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using ImageKit.Core;
using ImageKit.Models.Accounts.UrlEndpoints;

namespace ImageKit.Services.Accounts;

/// <summary>
/// NOTE: Do not inherit from this type outside the SDK unless you're okay with breaking
/// changes in non-major versions. We may add new methods in the future that cause
/// existing derived classes to break.
/// </summary>
public interface IUrlEndpointService
{
    /// <summary>
    /// Returns a view of this service that provides access to raw HTTP responses
    /// for each method.
    /// </summary>
    IUrlEndpointServiceWithRawResponse WithRawResponse { get; }

    /// <summary>
    /// Returns a view of this service with the given option modifications applied.
    ///
    /// <para>The original service is not modified.</para>
    /// </summary>
    IUrlEndpointService WithOptions(Func<ClientOptions, ClientOptions> modifier);

    /// <summary>
    /// **Note:** This API is currently in beta.   Creates a new URL‑endpoint and
    /// returns the resulting object.
    /// </summary>
    Task<UrlEndpointResponse> Create(
        UrlEndpointCreateParams parameters,
        CancellationToken cancellationToken = default
    );

    /// <summary>
    /// **Note:** This API is currently in beta.   Updates the URL‑endpoint identified
    /// by `id` and returns the updated object.
    /// </summary>
    Task<UrlEndpointResponse> Update(
        UrlEndpointUpdateParams parameters,
        CancellationToken cancellationToken = default
    );

    /// <inheritdoc cref="Update(UrlEndpointUpdateParams, CancellationToken)"/>
    Task<UrlEndpointResponse> Update(
        string id,
        UrlEndpointUpdateParams parameters,
        CancellationToken cancellationToken = default
    );

    /// <summary>
    /// **Note:** This API is currently in beta.   Returns an array of all URL‑endpoints
    /// configured including the default URL-endpoint generated by ImageKit during
    /// account creation.
    /// </summary>
    Task<List<UrlEndpointResponse>> List(
        UrlEndpointListParams? parameters = null,
        CancellationToken cancellationToken = default
    );

    /// <summary>
    /// **Note:** This API is currently in beta.   Deletes the URL‑endpoint identified
    /// by `id`. You cannot delete the default URL‑endpoint created by ImageKit during
    /// account creation.
    /// </summary>
    Task Delete(UrlEndpointDeleteParams parameters, CancellationToken cancellationToken = default);

    /// <inheritdoc cref="Delete(UrlEndpointDeleteParams, CancellationToken)"/>
    Task Delete(
        string id,
        UrlEndpointDeleteParams? parameters = null,
        CancellationToken cancellationToken = default
    );

    /// <summary>
    /// **Note:** This API is currently in beta.   Retrieves the URL‑endpoint identified
    /// by `id`.
    /// </summary>
    Task<UrlEndpointResponse> Get(
        UrlEndpointGetParams parameters,
        CancellationToken cancellationToken = default
    );

    /// <inheritdoc cref="Get(UrlEndpointGetParams, CancellationToken)"/>
    Task<UrlEndpointResponse> Get(
        string id,
        UrlEndpointGetParams? parameters = null,
        CancellationToken cancellationToken = default
    );
}

/// <summary>
/// A view of <see cref="IUrlEndpointService"/> that provides access to raw
/// HTTP responses for each method.
/// </summary>
public interface IUrlEndpointServiceWithRawResponse
{
    /// <summary>
    /// Returns a view of this service with the given option modifications applied.
    ///
    /// <para>The original service is not modified.</para>
    /// </summary>
    IUrlEndpointServiceWithRawResponse WithOptions(Func<ClientOptions, ClientOptions> modifier);

    /// <summary>
    /// Returns a raw HTTP response for <c>post /v1/accounts/url-endpoints</c>, but is otherwise the
    /// same as <see cref="IUrlEndpointService.Create(UrlEndpointCreateParams, CancellationToken)"/>.
    /// </summary>
    Task<HttpResponse<UrlEndpointResponse>> Create(
        UrlEndpointCreateParams parameters,
        CancellationToken cancellationToken = default
    );

    /// <summary>
    /// Returns a raw HTTP response for <c>put /v1/accounts/url-endpoints/{id}</c>, but is otherwise the
    /// same as <see cref="IUrlEndpointService.Update(UrlEndpointUpdateParams, CancellationToken)"/>.
    /// </summary>
    Task<HttpResponse<UrlEndpointResponse>> Update(
        UrlEndpointUpdateParams parameters,
        CancellationToken cancellationToken = default
    );

    /// <inheritdoc cref="Update(UrlEndpointUpdateParams, CancellationToken)"/>
    Task<HttpResponse<UrlEndpointResponse>> Update(
        string id,
        UrlEndpointUpdateParams parameters,
        CancellationToken cancellationToken = default
    );

    /// <summary>
    /// Returns a raw HTTP response for <c>get /v1/accounts/url-endpoints</c>, but is otherwise the
    /// same as <see cref="IUrlEndpointService.List(UrlEndpointListParams?, CancellationToken)"/>.
    /// </summary>
    Task<HttpResponse<List<UrlEndpointResponse>>> List(
        UrlEndpointListParams? parameters = null,
        CancellationToken cancellationToken = default
    );

    /// <summary>
    /// Returns a raw HTTP response for <c>delete /v1/accounts/url-endpoints/{id}</c>, but is otherwise the
    /// same as <see cref="IUrlEndpointService.Delete(UrlEndpointDeleteParams, CancellationToken)"/>.
    /// </summary>
    Task<HttpResponse> Delete(
        UrlEndpointDeleteParams parameters,
        CancellationToken cancellationToken = default
    );

    /// <inheritdoc cref="Delete(UrlEndpointDeleteParams, CancellationToken)"/>
    Task<HttpResponse> Delete(
        string id,
        UrlEndpointDeleteParams? parameters = null,
        CancellationToken cancellationToken = default
    );

    /// <summary>
    /// Returns a raw HTTP response for <c>get /v1/accounts/url-endpoints/{id}</c>, but is otherwise the
    /// same as <see cref="IUrlEndpointService.Get(UrlEndpointGetParams, CancellationToken)"/>.
    /// </summary>
    Task<HttpResponse<UrlEndpointResponse>> Get(
        UrlEndpointGetParams parameters,
        CancellationToken cancellationToken = default
    );

    /// <inheritdoc cref="Get(UrlEndpointGetParams, CancellationToken)"/>
    Task<HttpResponse<UrlEndpointResponse>> Get(
        string id,
        UrlEndpointGetParams? parameters = null,
        CancellationToken cancellationToken = default
    );
}
